import 'package:test/test.dart';
import 'package:sc4pac_gui/model.dart';

void main() {
  test('RingBuffer', () {
    final b = RingBuffer(capacity: 5);
    b.add(0);
    expect(b.length, equals(1));
    expect(b.takeRight(5), equals([0]));
    b.add(1);
    b.add(2);
    b.add(3);
    expect(b.length, equals(4));
    expect(b.takeRight(5), equals([0,1,2,3]));
    b.add(4);
    b.add(5);
    b.add(6);
    expect(b.length, equals(5));
    expect(b.takeRight(5), equals([2,3,4,5,6]));
    expect(b.takeRight(3), equals([4,5,6]));
    b.add(7);
    b.add(8);
    b.add(9);
    b.add(10);
    expect(b.length, equals(5));
    expect(b.takeRight(10), equals([6,7,8,9,10]));
    expect(b.takeRight(3), equals([8,9,10]));
    b.clear();
    expect(b.length, equals(0));
    b.add(11);
    b.add(12);
    b.add(13);
    b.add(14);
    b.add(15);
    b.add(16);
    expect(b.removeLast(), equals(16));
    expect(b.removeLast(), equals(15));
    expect(b.removeLast(), equals(14));
    expect(b.last, equals(13));
    expect(b.takeRight(10), equals([12,13]));
    expect(b.remaining, equals(3));
  });
  test('MruCache', () {
    final c = MruCache<String, int>(capacity: 3);
    c['a'] = 1;
    expect(c['a'], equals(1));
    expect(c.keys, equals(['a']));
    c['b'] = 2;
    c['c'] = 3;
    expect(c['b'], equals(2));
    c['d'] = 4;
    expect(c.keys, equals(['c', 'b', 'd']));
    c['c'] = 5;
    expect(c.keys, equals(['b', 'd', 'c']));
    c['d'];
    expect(c.keys, equals(['b', 'c', 'd']));
    c['a'];
    expect(c.keys, equals(['b', 'c', 'd']));
    c['a'] = 6;
    expect(c.keys, equals(['c', 'd', 'a']));
  });
}
